export const FETCH_DATA_START = 'FETCH_DATA_START';

export const CHECK_AUTH_SUCCESS = 'CHECK_AUTH_SUCCESS';
export const CHECK_AUTH_FAIL = 'CHECK_AUTH_FAIL';

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOGOUT_START = 'LOGOUT_START';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';

export const COURSES_START = 'COURSES_START';
export const COURSES_SUCCESS = 'COURSES_SUCCESS';
export const COURSES_FAIL = 'COURSES_FAIL';

export const COURSE_PROJECT_START = 'COURSE_PROJECT_START';
export const COURSE_PROJECT_SUCCESS = 'COURSE_PROJECT_SUCCESS';
export const COURSE_PROJECT_FAIL = 'COURSE_PROJECT_FAIL';

export const COURSE_ASSIGNMENT_START = 'COURSE_ASSIGNMENT_START';
export const COURSE_ASSIGNMENT_SUCCESS = 'COURSE_ASSIGNMENT_SUCCESS';
export const COURSE_ASSIGNMENT_FAIL = 'COURSE_ASSIGNMENT_FAIL';

export const COURSE_FILE_START = 'COURSE_FILE_START';
export const COURSE_FILE_SUCCESS = 'COURSE_FILE_SUCCESS';
export const COURSE_FILE_FAIL = 'COURSE_FILE_FAIL';

export const COURSE_VIDEO_START = 'COURSE_VIDEO_START';
export const COURSE_VIDEO_SUCCESS = 'COURSE_VIDEO_SUCCESS';
export const COURSE_VIDEO_FAIL = 'COURSE_VIDEO_FAIL';

export const PROFILE_START = 'PROFILE_START';
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';
export const PROFILE_FAIL = 'PROFILE_FAIL';

export const PROFILE_UPDATE_START = 'PROFILE_UPDATE_START';
export const PROFILE_UPDATE_FAIL = 'PROFILE_UPDATE_FAIL';
export const PROFILE_UPDATE_SUCCESS = 'PROFILE_UPDATE_SUCCESS';

export const PROFILE_DELETE_START = 'PROFILE_DELETE_START';
export const PROFILE_DELETE_FAIL = 'PROFILE_DELETE_FAIL';
export const PROFILE_DELETE_SUCCESS = 'PROFILE_DELETE_SUCCESS';

export const USER_UPDATE_START = 'USER_UPDATE_START';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';

export const USER_DATA_START = 'USER_DATA_START';
export const USER_DATA_SUCCESS = 'USER_DATA_SUCCESS';
export const USER_DATA_FAIL = 'USER_DATA_FAIL';

export const OPEN_LOG_OUT_MODAL = 'OPEN_LOG_OUT_MODAL';
export const CLOSE_LOG_OUT_MODAL = 'CLOSE_LOG_OUT_MODAL';

export const SET_CROPPED_IMAGE_NAME = 'SET_CROPPED_IMAGE_NAME';



